name: Deploy to Oracle VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd ~/VM-ORACLE-2
            git pull origin main
            npm install @whiskeysockets/baileys@latest
            npm install
            pm2 restart bmm || pm2 start src/index.js --name bmm
            # Wait for the bot to fully initialize
            sleep 60
            # Send update notifications with the correct version
            node scripts/notifyUpdate.js
